### ISSUE TITLE
Do you have script of evaluation part? 

### ISSUE THREAD

**Issue by phaphuang** [MJ10/BioSeq-GFN-AL#3]
Hello, could you provide the evaluation script? To better evaluate the performance of model.

**Comment by MJ10** [comment]
Hi, apologies for the late response, the code for evaluation (which logs the metrics) is already in the repo: https://github.com/MJ10/BioSeq-GFN-AL/blob/master/run_amp.py#L342

**Comment by dlnp2** [comment]
@MJ10 Can I ask you a related question: How to reproduce the results in Table 3 of your paper? Specifically, how to "re-normalize" the GFP scores as mentioned in A.3 section? I tried `run_gfp.py` and got values like 1.4354270063340664 as top-128-scores, which seemed not to be normalized. Do you have any specific code in the repo?
